#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xset s off -dpms & # disable power management (monitor will stay on)
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
gsettings set org.gnome.desktop.interface color-scheme prefer-dark &
picom --experimental-backend  & # for nice blur, animations and rounded corners!
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
sleep 10 && aw-qt &

# Per host:
if [ "$(hostname)" = "larch" ]; then
	brightnessctl s 100 &		# max brightness

if [ "$(hostname)" = "archlinux" ]; then
	xrandr --output HDMI-A-1 --mode 1920x1080 --rate 74.97 --dpi 96 --set TearFree on --primary --output DisplayPort-1 --mode 1920x1080 --rate 144.00 --dpi 96 --set TearFree on --right-of HDMI-A-1 --noprimary &

autostart="mpd dunst unclutter pipewire udiskie nm-applet blueman-applet gotify-desktop musnify-mpd thunderbird discord"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"


sleep 5 && notify-send "Welcome to $(hostname)" "enjoy your stay!"
