#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bc="bc -ql" \
	yt="yt-dlp --sponsorblock-mark all --sponsorblock-remove sponsor,interaction,selfpromo,outro --write-subs --write-auto-subs --embed-subs --sub-langs 'en,nl' --compat-options no-keep-subs --embed-metadata -o '%(title)s.%(ext)s' -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"\
	hugoserver="hugo server --noHTTPCache"\
    sxiv="nsxiv"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	la="ls -a" \
	ll="ls -al" \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="ytfzf -t --thumbnail-quality=maxres --notify-playing --preview-side=left" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
    t="task" \
	browser-sync='browser-sync start --server --files "**/*"' \
    mpv-empty="mpv --force-window"\
    merge-pdf="qpdf --empty --pages *.pdf -- "



alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
